#https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/common-application-properties.html

spring:
    application:
        name: multitenancy
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456
#    flyway:
#        enabled: false

#spring.jpa.hibernate.ddl-auto=create


server:
    port: 8989

#debug: true
logging:
    level:
        com.example.multitenancy.*: TRACE